use_api: true

session_key: "SECRET_SESSION_SECRET"

game:
  folder_id: "test"

url:
  web: //localhost:4000
  api: //localhost:4000/api
#  api: //giji.f5.si/api
  sow: https://s3-ap-northeast-1.amazonaws.com/giji-assets/sow

  store: https://s3-ap-northeast-1.amazonaws.com/giji-assets

db:
  mongo: mongodb://localhost/giji
  mongo_sow: mongodb://localhost/giji
